[package]
name = "osus-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
env_logger = "0.9.0"
log = "0.4.17"
osus = { path = "../osus" }
walkdir = "2.3.2"