[package]
name = "osus"
version = "0.1.0"
authors = ["Speykious <speykious@gmail.com>"]
edition = "2021"

[dependencies]
env_logger = "0.9.0"
error-stack = "0.1.1"
log = "0.4.17"
thiserror = "1.0.31"

[dev-dependencies]
clap = { version = "4.0.18", features = ["derive"] }
walkdir = "2.3.2"
