[package]
name = "osus"
version = "0.1.0"
description = "Library for various osu! utilities and scripts."
authors = ["Speykious <speykious@gmail.com>"]
edition = "2021"

[dependencies]
error-stack = "0.1.1"
log = "0.4.17"
thiserror = "1.0.31"

